apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trema
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: trema=ghcr.io/clubcedille/trema:latest
    argocd-image-updater.argoproj.io/trema.update-strategy: digest
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: trema
  source:
    repoURL: https://github.com/ClubCedille/Plateforme-Cedille
    path: apps/trema/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
