apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-provider
  namespace: calidum-rotae
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-provider
  template:
    metadata:
      labels:
        app: email-provider
      annotations:
        # vault.hashicorp.com/agent-inject: 'true'
        # vault.hashicorp.com/tls-skip-verify: 'true'
        # vault.hashicorp.com/role: 'secret-reader'
        # vault.hashicorp.com/agent-inject-template-email-provider-env: |
        #   {{- with secret "kv/calidum-rotae/default/email-provider-env" -}}
        #     export EMAIL_SENDGRID_API_KEY="{{ .Data.data.email_sendgrid_api_key }}"
        #   {{- end }}
    spec:
      containers:
        - name: email-provider
          image: ghcr.io/clubcedille/email-provider:1.0.1
          imagePullPolicy: Always
          command:
            # ['/bin/sh', '-c', 'source /vault/secrets/email-provider-env && /email_provider --port 4000']
            ['/bin/sh', '-c', '/email_provider --port 4000']
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: email-provider-env
          env:
            - name: EMAIL_SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: calidum-rotae-secrets
                  key: EMAIL_SENDGRID_API_KEY
