apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saveurdegenie
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: saveurdegenie
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-prod
    path: apps/saveurdegenie/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true
