apiVersion: v1
kind: Service
metadata:
  name: wiki-cedille
spec:
  selector:
    app: wiki-cedille
  ports:
    - name: http
      targetPort: 8080
      protocol: TCP
      port: 80
  type: ClusterIP