apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-cedille
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: wiki=ghcr.io/clubcedille/wiki-cedille:latest
    argocd-image-updater.argoproj.io/wiki.update-strategy: digest
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: wiki-cedille
  source:
    repoURL: https://github.com/ClubCedille/Plateforme-Cedille
    path: apps/wiki-cedille/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
