apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wiki-sonia
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
      - name: wikijs
        image: requarks/wiki:2.5.292
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: DB_TYPE
          value: "postgres"
        - name: DB_USER
          value: "wiki"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: wikijs-secrets
              key: DB_PASS
        - name: DB_NAME
          value: "wiki_sonia"
        - name: DB_HOST
          value: "postgres.wiki-sonia.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_POOL_MIN
          value: "0"
        - name: DB_POOL_MAX
          value: "5"
        - name: DB_SSL
          value: "false"
          
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 3
