apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wiki-sonia
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
      - name: wikijs
        image: requarks/wiki:2.5.292
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: wikijs-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wikijs-secrets
              key: DB_PASS
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: wikijs-secrets
              key: DB_NAME
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: wiki-sonia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: wikijs-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wikijs-secrets
              key: DB_PASS
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: wikijs-secrets
              key: DB_NAME
        ports:
        - containerPort: 5432
