apiVersion: v1
kind: Service
metadata:
  name: wikijs
  namespace: wiki-sonia
spec:
  ports:
  - name: wikijs
    port: 3000
    targetPort: 3000
  type: ClusterIP
  selector:
    app: wikijs
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: wiki-sonia
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres
