apiVersion: v1
kind: Service
metadata:
  name: wikijs
  namespace: wiki-sonia
spec:
  ports:
  - name: wikijs
    port: 3000
    targetPort: 3000
  type: ClusterIP
  selector:
    app: wiki-sonia
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: wiki-sonia
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: postgres
