apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synapsets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: synapse=clubcedille/synapsets.etsmtl.ca:latest
    argocd-image-updater.argoproj.io/synapse.update-strategy: digest
spec:
  project: default
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-production
    namespace: synapsets
  source:
    repoURL: https://github.com/ClubCedille/k8s-cedille-production
    path: apps/synapsets/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true
