apiVersion: apps/v1
kind: Deployment
metadata:
  name: trema
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trema
  template:
    metadata:
      labels:
        app: trema
    spec:
      containers:
        - name: trema
          image: ghcr.io/clubcedille/trema:latest
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 6000
          readinessProbe:
            exec:
              command:
                - python
                - /app/scripts/check_db.py
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: API_ADDRESS
              value: "0.0.0.0"
            - name: API_PORT
              value: "6000"
            - name: MONGO_HOST
              value: "mongo.trema.svc.cluster.local"
            - name: MONGO_USER
              value: "trema"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trema-env-secret
                  key: mongo_password
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: trema-env-secret
                  key: discord_token
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: trema-env-secret
                  key: github_token
            - name: CALIDUM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trema-env-secret
                  key: calidum_api_key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:8.0.0
          imagePullPolicy: Always
          resources: {}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "trema"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trema-env-secret
                  key: mongo_password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: local-hostpath
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
